# Generated by Django 4.2.3 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='another_field',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
