# Generated by Django 4.2.3 on 2023-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_demo_another_field_demo_my_custom_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='another_field',
            field=models.IntegerField(),
        ),
    ]
